version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: tournament
      POSTGRES_USER: tournament
      POSTGRES_DB: tournament

  tgbot:
    build:
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data/media:/data/media
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}